services:
  php:
    image: php:8.2-apache
    container_name: phpApacheBook
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysqlBook
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: bookeo
      MYSQL_USER: gwld
      MYSQL_PASSWORD: passgwld
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminBook
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: gwld
      PMA_PASSWORD: passgwld
    ports:
      - 8899:80

volumes:
  db_data:
